spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/loandb
    username: postgres
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

loan:
  minimalIncome: 40000
  minimalCarPrice: 1000000
  incomePercentage: 0.5
  carPricePercentage: 0.3
  carMinPriceRange: 800000
  carMaxPriceRange: 1200000
